CREATE DATABASE banking_system;

CREATE TABLE USERS (
    ID_USER SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PATRONYMIC VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE BANKS (
    ID_BANK serial NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    NUMBER_OF_EMPLOYEES int NOT NULL DEFAULT 1
);

CREATE TABLE CHECKING_ACCOUNT (
    NUMBER_CHECKING_ACCOUNT serial NOT NULL PRIMARY KEY,
    ACCOUNT_TYPE VARCHAR(255) NOT NULL,
    STATUS_ACCOUNT VARCHAR(255) NOT NULL,
    OPENING_DATA DATE NOT NULL,
    BALANCE MONEY NOT NULL DEFAULT 0,
    ACCOUNT_CURRENCY VARCHAR(5) NOT NULL DEFAULT 'BYN',
    ID_USER INT NOT NULL REFERENCES USERS(ID_USER),
    ID_BANK INT NOT NULL REFERENCES BANKS(ID_BANK)
);

CREATE TABLE TRANSACTIONS (
    ID_TRANSACTION serial NOT NULL PRIMARY KEY,
    TYPE_TRANSACTION VARCHAR(255) NOT NULL,
    SENDERS_BANK_ACCOUNT int NOT NULL REFERENCES CHECKING_ACCOUNT(NUMBER_CHECKING_ACCOUNT),
    RECIPIENT_BANK_ACCOUNT int NOT NULL REFERENCES CHECKING_ACCOUNT(NUMBER_CHECKING_ACCOUNT),
    TRANSFER_AMOUNT MONEY NOT NULL DEFAULT 2,
    TRANSFER_STATUS VARCHAR(255) NOT NULL DEFAULT 'Выполнено'
);